### ISSUE TITLE
Do we have a KGS of dependencies?

### ISSUE THREAD

**Issue by hvelarde** [collective/pas.plugins.ldap#31]
pas.plugins.ldap has a lot of dependencies that need to be pinned; do we have a known good set of versions that we must use with current release 1.5.1?

**Comment by rnixx** [comment]
AFAIK a lot of this dependencies are defined because the plugin works in plain Zope. I also think that there are some redundant dependencies (@jensens?) which are basically subsequent dependencies of other packages. Plone related packages should also not be pinned, because the plugin works with Plone 4 and Plone 5 and the related versions are pinned down at other places. Are some bluedynamics originated packages left for which we can define latest releases if we want, not sure whether it makes much sense though.

Do you have some specific problems with your setup right now you're trying to solve with a KGS?

**Comment by hvelarde** [comment]
no, I just wanted to know how to pin it in production.
