### ISSUE TITLE
Package tries to contact LDAP server even when not installed

### ISSUE THREAD

**Issue by hvelarde** [collective/pas.plugins.ldap#35]
I have the package unistalled and I can see the following in the event log:

```
2016-12-16T14:31:19 WARNING pas.plugins.ldap LDAPError in authenticateCredentials -> {'desc': "Can't contact LDAP server"}
------
2016-12-16T14:36:25 WARNING pas.plugins.ldap LDAPError in authenticateCredentials -> {'desc': "Can't contact LDAP server"}
```

**Comment by hvelarde** [comment]
I think this has nothing to do with uninstaller; IIRC, I never installed the package in the first place and it's trying to contact the LDAP server anyway.

**Comment by rnixx** [comment]
Steps to reproduce please.

**Comment by hvelarde** [comment]
I think this is an effect of the problem described in #25.

**Comment by jensens** [comment]
The plugin can only work if it is installed, since only then an instance of it is created in ``acl_users``. If there is no instance it is impossible to have code running connecting to LDAP.

**Comment by jensens** [comment]
Btw, I left the plugin intentionally behind. Otherwise its settings are vanished. And since people like to click in Add-Ons control-panel on uninstall/ install, because they believe it would fix something, this is probably a good idea. 

We may want to disable the plugin in plugin registry on uninstall and enable it there if it is already there.

**Comment by rnixx** [comment]
@jensens - valid point, never thought about it this way
